sudo: required

services:
  - docker

before_install:
- docker build -t cavedbmanager -f Dockerfile.web .
- docker ps -a

script:
- docker run --name app -ti cavedbmanager make ci

after_script:
- docker rm -f app
