sudo: required

services:
  - docker

before_install:
- docker build --file Dockerfile.base --tag cavedbmanager_base:latest .
- docker build -t cavedbmanager -f Dockerfile.web .
- docker images -a
- docker ps -a

script:
- docker run --name app -ti cavedbmanager make ci

after_script:
- docker rm -f app
