FROM ubuntu:18.04

MAINTAINER Brian Masney <masneyb@onstation.org>

ENV TZ=America/New_York

VOLUME ["/var/run/cavedb-worker"]

RUN apt-get update && apt-get -y install cron

COPY conf/crontab /etc/crontab.template

COPY cavedb/scripts/docker-cron-entrypoint.sh /docker-cron-entrypoint.sh

ENTRYPOINT ["/docker-cron-entrypoint.sh"]
