FROM cavedbmanager_base

RUN export DEBIAN_FRONTEND=noninteractive && \
    apt-get update && \
    apt-get install --no-install-recommends -y nginx ssl-cert supervisor uwsgi \
                                               uwsgi-plugin-python3 && \
    rm -rf /usr/share/doc /usr/share/man && \
    (rm /var/lib/apt/lists/* || true) && \
    apt-get clean && \
    echo "daemon off;" >> /etc/nginx/nginx.conf && \
    mkdir -m 0700 /var/run/uwsgi/ && \
    chown www-data:www-data /var/run/uwsgi/

COPY conf/nginx-app.conf /etc/nginx/sites-available/default
COPY conf/supervisord.conf /etc/supervisor/conf.d/supervisord.conf
COPY conf/uwsgi.ini /etc/uwsgi/

VOLUME ["/usr/local/cavedbmanager-data", "/var/run/cavedb-worker"]

EXPOSE 80

COPY . /usr/local/cavedbmanager

WORKDIR /usr/local/cavedbmanager
