FROM debian:stretch

MAINTAINER Brian Masney <masneyb@onstation.org>

ENV TZ=America/New_York
RUN ln -snf /usr/share/zoneinfo/${TZ} /etc/localtime && echo ${TZ} > /etc/timezone

RUN apt-get update && \
    apt-get install --no-install-recommends -y gosu postgis postgresql-9.6 \
                                               postgresql-9.6-postgis-2.3 \
                                               postgresql-9.6-postgis-scripts && \
    rm -rf /usr/share/doc /usr/share/man && \
    (rm /var/lib/apt/lists/* || true) && \
    apt-get clean

COPY cavedb/scripts/docker-db-entrypoint.sh /docker-db-entrypoint.sh

VOLUME ["/var/lib/postgresql"]

ENTRYPOINT ["/docker-db-entrypoint.sh"]
