FROM alpine:3.4

MAINTAINER Brian Masney <masneyb@onstation.org>

RUN apk add --update-cache dcron && \
    rm -rf /var/cache/apk/*

COPY conf/crontab /etc/crontabs/root

VOLUME ["/tmp/cavedb-worker"]

# dcron fails with this error if it is the entrypoint:
# setpgid: Operation not permitted
# Calling it from a shell fixes the issue.

ENTRYPOINT ["/bin/sh", "-c", "/usr/sbin/crond -f"]
