version: '2'
services:
  postgresql:
    image: "mdillon/postgis:9.5"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    expose:
      - "5432"
    volumes:
     - ./docker-tmp/var-lib-postgresql-data:/var/lib/postgresql/data
  web:
    build: .
    ports:
     - "8000:8000"
    depends_on:
     - postgresql
    volumes:
     - ./docker-tmp/postgis-data-importer-downloads:/usr/local/postgis-data-importer/download
    entrypoint:
     - ./docker-entrypoint.sh
    environment:
     - PGHOST=postgresql
     - PGPORT=5432
     - PGDATABASE=cavedb
     - PGUSER=root
     - PGPASSWORD=root
     - WEB_ADMIN_EMAIL=user@domain.com
     - WEB_ADMIN_FULLNAME=Your Name
     - WEB_ADMIN_USER=admin
     - WEB_ADMIN_PASS=password
     - CAVEDB_DEBUG=1
     - CAVEDB_SITE_HEADER=My Cave Database
     - CAVEDB_SECRET_KEY=FIXME_CHANGE_THIS_SECRET_KEY
     # Separate multiple hosts with a :
     - CAVEDB_ALLOWED_HOSTS=localhost
