<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0">
<xsl:output method="text" indent="no" encoding="US-ASCII"/>

<xsl:param name="SHOW_ON_MAPS"/>
<xsl:param name="INCLUDE"/>
<xsl:param name="OVERRIDE_LABEL_COLOR"/>

<xsl:template match="/regions">
  <xsl:text>MAP
  # Automatically generated by xml2mapserver_project.xsl
  IMAGETYPE      JPEG
  SIZE           2100 2100
  IMAGECOLOR     255 255 255
  FONTSET         "fonts.list"

  OUTPUTFORMAT
    NAME "aggjpg24"
    DRIVER AGG/JPEG
    MIMETYPE "image/jpeg"
    IMAGEMODE RGB
    EXTENSION "jpg"
  END

  SYMBOL
    NAME "punkt"
    TYPE ELLIPSE
    POINTS
      1 1
    END
    FILLED TRUE
  END

  SYMBOL
    NAME "trail"
    TYPE ellipse
    POINTS 1 1 END
    FILLED TRUE
    #PATTERN 1 2 END
  END

  SYMBOL
    NAME "railway"
    TYPE ellipse
    POINTS 2 2 END
    FILLED TRUE
    #PATTERN 3 3 END
  END

  UNITS dd
  PROJECTION
    "proj=longlat"
    "ellps=WGS84"
    "datum=WGS84"
    "no_defs"
  END

  LEGEND
    KEYSIZE 36 36
    LABEL
      SIZE 24
      TYPE TRUETYPE
      FONT opensymbol
      ANTIALIAS TRUE
  </xsl:text>

  <xsl:call-template name="show_label_color">
    <xsl:with-param name="color">0 0 89</xsl:with-param>
  </xsl:call-template>

  <xsl:text>      POSITION cc
    END
    STATUS OFF
    POSITION lr
    IMAGECOLOR 255 255 255
    TRANSPARENT FALSE
  END

  SCALEBAR
    LABEL
      SIZE 20
      TYPE TRUETYPE
      FONT opensymbol
      ANTIALIAS TRUE
      COLOR 0 0 0
    END
    STYLE 0
    SIZE 600 25
    IMAGECOLOR 255 255 255
    OUTLINECOLOR 0 0 0
    TRANSPARENT FALSE
    COLOR 0 0 0
    UNITS MILES
    INTERVALS 5
    STATUS EMBED
    POSITION ll
  END

</xsl:text>

  <xsl:if test="$INCLUDE != ''">
    <xsl:text>  INCLUDE "</xsl:text>
    <xsl:value-of select="$INCLUDE"/>
    <xsl:text>"

</xsl:text>
  </xsl:if>

  <xsl:for-each select="gis_layers/gis_layer[show_on_maps='Both' or show_on_maps=$SHOW_ON_MAPS]">
     <xsl:text>  LAYER
    NAME </xsl:text>
     <xsl:value-of select="name"/>
     <xsl:text>
</xsl:text>

     <xsl:if test="type != 'RASTER'">
       <xsl:text>    CONNECTIONTYPE </xsl:text>
       <xsl:value-of select="connection_type"/>

       <xsl:text>
    CONNECTION "</xsl:text>
       <xsl:value-of select="connection"/>

       <xsl:text>"
</xsl:text>
     </xsl:if>

     <xsl:text>    DATA "</xsl:text>
     <xsl:value-of select="data"/>
     <xsl:text>"
</xsl:text>

     <xsl:choose>
       <xsl:when test="display = '1'">
         <xsl:text>    STATUS ON
</xsl:text>
       </xsl:when>
       <xsl:otherwise>
         <xsl:text>    STATUS OFF
</xsl:text>
       </xsl:otherwise>
     </xsl:choose>

     <xsl:text>    TYPE </xsl:text>
     <xsl:value-of select="type"/>
     <xsl:text>
</xsl:text>

     <xsl:if test="label_item">
       <xsl:text>    LABELITEM "</xsl:text>
       <xsl:value-of select="label_item"/>
       <xsl:text>"
</xsl:text>
     </xsl:if>

     <xsl:if test="type != 'RASTER'">
       <xsl:text>    CLASS
      COLOR </xsl:text>
       <xsl:value-of select="color/@red"/>
       <xsl:text> </xsl:text>
       <xsl:value-of select="color/@green"/>
       <xsl:text> </xsl:text>
       <xsl:value-of select="color/@blue"/>
       <xsl:text>
</xsl:text>

       <xsl:if test="legend/@first_occurance='1'">
         <xsl:text>      NAME "</xsl:text>
         <xsl:value-of select="legend"/>
         <xsl:text>"
</xsl:text>
       </xsl:if>

       <xsl:if test="symbol != ''">
         <xsl:text>      SYMBOL "</xsl:text>
         <xsl:value-of select="symbol"/>
         <xsl:text>"
      SIZE </xsl:text>
         <xsl:value-of select="symbol_size"/>
         <xsl:text>
</xsl:text>
       </xsl:if>

       <xsl:if test="max_scale != ''">
         <xsl:text>      MAXSCALE </xsl:text>
         <xsl:value-of select="max_scale"/>
         <xsl:text>
</xsl:text>
       </xsl:if>

       <xsl:if test="label_item">
         <xsl:text>      LABEL
        ANGLE AUTO
        TYPE TRUETYPE
        FONT opensymbol
        ANTIALIAS TRUE
        POSITION AUTO
        PARTIALS TRUE
        MINDISTANCE 500
        BUFFER 20
        MINSIZE 4
</xsl:text>

          <xsl:call-template name="show_label_color">
            <xsl:with-param name="color">
              <xsl:value-of select="font_color/@red"/>
              <xsl:text> </xsl:text>
              <xsl:value-of select="font_color/@green"/>
              <xsl:text> </xsl:text>
              <xsl:value-of select="font_color/@blue"/>
            </xsl:with-param>
          </xsl:call-template>

          <xsl:text>        SIZE </xsl:text>
          <xsl:value-of select="font_size * 2"/>
          <xsl:text>
      END
</xsl:text>
       </xsl:if>

       <xsl:text>    END
</xsl:text>
     </xsl:if>

     <xsl:text>  END
</xsl:text>
  </xsl:for-each>

  <xsl:for-each select="gis_layers/lineplot[type='underground']">
     <xsl:text>  LAYER
    NAME lineplot_</xsl:text>
     <xsl:value-of select="id"/>

     <xsl:text>
    DATA "</xsl:text>
     <xsl:value-of select="file"/>
     <xsl:text>"
    STATUS ON
    TYPE LINE
</xsl:text>

    <xsl:choose>
      <xsl:when test="coord_sys='UTM' and datum='NAD27'">
        <xsl:text>    PROJECTION
      "proj=utm"
      "zone=17"
      "ellps=clrk66"
      "datum=NAD27"
      "units=m"
      "no_defs"
    END
</xsl:text>
      </xsl:when>
      <xsl:when test="coord_sys='LATLON' and (datum='NAD83' or datum='WGS84')">
        <xsl:text>    PROJECTION
      "proj=longlat"
      "ellps=WGS84"
      "datum=WGS84"
      "no_defs"
    END
</xsl:text>
      </xsl:when>
    </xsl:choose>

    <xsl:text>    CLASS
      SYMBOL "punkt"
      SIZE 2
      MAXSCALE 60000.00
</xsl:text>

    <xsl:choose>
      <xsl:when test="$OVERRIDE_LABEL_COLOR != ''">
        <xsl:text>      COLOR </xsl:text>
        <xsl:value-of select="$OVERRIDE_LABEL_COLOR"/>
        <xsl:text>
</xsl:text>
      </xsl:when>
      <xsl:otherwise>
        <xsl:text>      COLOR 255 0 0
</xsl:text>
      </xsl:otherwise>
    </xsl:choose>

    <xsl:text>    END
  END
</xsl:text>
  </xsl:for-each>

  <xsl:text>  LAYER
    NAME karst_feature_locations
    DATA ../shp/karst_feature_locations
    STATUS ON
    TYPE POINT
    PROJECTION
      "proj=longlat"
      "ellps=WGS84"
      "datum=WGS84"
      "no_defs"
    END
    LABELITEM       "name"
    CLASS
      EXPRESSION ('[significan]' eq 'yes')
      SYMBOL  "punkt"
      SIZE    7
</xsl:text>

  <xsl:call-template name="output_feature_color"/>

  <xsl:text>      MAXSCALE 60000.00
      LABEL
        ANGLE 45
        TYPE TRUETYPE
        FONT opensymbol
        ANTIALIAS TRUE
        POSITION AUTO
        PARTIALS TRUE
        MINDISTANCE 50
        BUFFER 4
        MINSIZE 4
</xsl:text>

  <xsl:call-template name="show_label_color">
    <xsl:with-param name="color">132 31 31</xsl:with-param>
  </xsl:call-template>

  <xsl:text>        SIZE 16
        PRIORITY [gislbl_pri]
      END
    END

    CLASS
      EXPRESSION ('[type]' eq 'Cave')
      SYMBOL  "punkt"
      SIZE    7
</xsl:text>

  <xsl:call-template name="output_feature_color"/>

  <xsl:text>      MAXSCALE 60000.00
      LABEL
        ANGLE 45
        TYPE TRUETYPE
        FONT opensymbol
        ANTIALIAS TRUE
        POSITION AUTO
        PARTIALS TRUE
        MINDISTANCE 50
        BUFFER 4
        MINSIZE 4
</xsl:text>

  <xsl:call-template name="show_label_color">
    <xsl:with-param name="color">132 31 31</xsl:with-param>
  </xsl:call-template>

  <xsl:text>        SIZE 14
        PRIORITY [gislbl_pri]
      END
    END

    CLASS
      EXPRESSION ('[type]' eq 'FRO' or '[type]' eq 'Sandstone')
      SYMBOL  "punkt"
      SIZE    5
</xsl:text>

  <xsl:call-template name="output_feature_color"/>

  <xsl:text>      MAXSCALE 60000.00
      LABEL
        ANGLE 45
        TYPE TRUETYPE
        FONT opensymbol
        ANTIALIAS TRUE
        POSITION AUTO
        PARTIALS TRUE
        MINDISTANCE 50
        BUFFER 4
        MINSIZE 4
</xsl:text>

  <xsl:call-template name="show_label_color">
    <xsl:with-param name="color">132 31 31</xsl:with-param>
  </xsl:call-template>

  <xsl:text>        SIZE 12
        PRIORITY [gislbl_pri]
      END
    END
  END

  LAYER
    NAME region_extents
    DATA ../shp/region_extents
    STATUS  ON
    TYPE  POLYGON
    PROJECTION
      "proj=longlat"
      "ellps=WGS84"
      "datum=WGS84"
      "no_defs"
    END

    LABELITEM "region_nam"

    CLASS
      OUTLINECOLOR   255 0 0
      MINSCALE 60000
      LABEL
        COLOR 132 31 31
        OUTLINECOLOR 255 255 255
        OUTLINEWIDTH 3
        TYPE TRUETYPE
        FONT opensymbol
        SIZE 14
        ANTIALIAS TRUE
        POSITION cc
        PARTIALS TRUE
        MINDISTANCE 0
        BUFFER 0
        FORCE TRUE
      END
    END
  END

  LAYER
    NAME "grid"
    TYPE LINE
    STATUS ON

    CLASS
      COLOR 112 128 144
      MINSCALE 60000
      LABEL 
        TYPE TRUETYPE
        FONT opensymbol
        SIZE 12
        POSITION AUTO
        PARTIALS FALSE
        BUFFER 50
        MINDISTANCE 10000000
        ANGLE AUTO
        POSITION cr
</xsl:text>

  <xsl:call-template name="show_label_color">
    <xsl:with-param name="color">255 0 0</xsl:with-param>
  </xsl:call-template>

  <xsl:text>      END
    END

    GRID
      LABELFORMAT DDMMSS
      MININTERVAL 0.125
      MAXINTERVAL 0.125
    END
  END

  LAYER
    NAME "grid_small"
    TYPE LINE
    STATUS ON
    CLASS
      COLOR 112 128 144
      MAXSCALE 60000
      LABEL 
        TYPE TRUETYPE
        FONT opensymbol
        SIZE 12
        POSITION AUTO
        PARTIALS FALSE
        BUFFER 50
        MINDISTANCE 10000000
        ANGLE AUTO
        POSITION cr
</xsl:text>

  <xsl:call-template name="show_label_color">
    <xsl:with-param name="color">255 0 0</xsl:with-param>
  </xsl:call-template>

  <xsl:text>      END
    END

    GRID
      LABELFORMAT DDMMSS
      MININTERVAL 0.01666666666666666666
      MAXINTERVAL 0.01666666666666666666
    END
  END
END
</xsl:text>

</xsl:template>

<xsl:template name="show_label_color">
  <xsl:param name="color"/>

  <xsl:variable name="shown_color">
    <xsl:choose>
      <xsl:when test="$OVERRIDE_LABEL_COLOR != ''">
        <xsl:value-of select="$OVERRIDE_LABEL_COLOR"/>
      </xsl:when>
      <xsl:otherwise>
        <xsl:value-of select="$color"/>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:variable>

  <xsl:if test="$shown_color != '255 255 255'">
    <xsl:text>        OUTLINECOLOR 255 255 255
        OUTLINEWIDTH 3
</xsl:text>
  </xsl:if>

  <xsl:text>        COLOR </xsl:text>
  <xsl:value-of select="$shown_color"/>
  <xsl:text>
</xsl:text>
</xsl:template>

<xsl:template name="output_feature_color">
  <xsl:choose>
    <xsl:when test="$OVERRIDE_LABEL_COLOR != ''">
      <xsl:text>      COLOR   </xsl:text>
      <xsl:value-of select="$OVERRIDE_LABEL_COLOR"/>
      <xsl:text>
</xsl:text>
    </xsl:when>
    <xsl:otherwise>
      <xsl:text>      COLOR   0 0 0
</xsl:text>
    </xsl:otherwise>
  </xsl:choose>
</xsl:template>

</xsl:stylesheet>
